### ISSUE TITLE
source code improvements

### ISSUE THREAD

**Issue by GUILHERMEPSANTOS** [GUILHERMEPSANTOS/Nexum#22]
- [x] Yaml ▶️  to application configs 
- [x] Jwt - probably``

```
 spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Nexum;encrypt=false;
    username: root
    password: '@Planeta2011'
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2016Dialect
      ddl-auto: update
``` 
references to JWT 

- references to ['JWT'](https://auth0.com/docs/quickstart/backend/java-spring-security5/interactive).
